- name: APT | Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: APT | Install gpsd packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - ntpsec

- name: NTPSEC | Configure ntpsec
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntpsec/ntp.conf
    owner: root
    group: root
    mode: "0644"

- name: NTPSEC | Enable ntpsec service
  ansible.builtin.systemd:
    name: ntpsec
    enabled: true
    state: started

- name: NTPSEC | Restart ntpsec service
  ansible.builtin.systemd:
    name: ntpsec
    state: restarted
