# code: language=ansible
- name: Provision a stratum 1 NTP server
  hosts: all
  user: root
  become: true
  become_method: sudo


  roles:
    - role: bootstrap
      tags: bootstrap

    - role: log2ram
      tags: log2ram

    - role: gpsd
      tags: gpsd

    - role: ntpsec
      tags: ntpsec

    - role: node_exporters
      tags: node_exporters

  tasks:
    - name: Reboot
      ansible.builtin.reboot:
