- name: APT | Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: APT | Install gpsd packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - chrony

- name: CHRONY | Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"

- name: CHRONY | Enable chrony service
  ansible.builtin.systemd:
    name: chrony
    enabled: true
    state: started

- name: CHRONY | Restart chrony service
  ansible.builtin.systemd:
    name: chrony
    state: restarted
